"""Hash tokens

Revision ID: 135698105a8d
Revises: afdd235cd4a9
Create Date: 2021-05-12 11:14:03.781573

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '135698105a8d'
down_revision = 'afdd235cd4a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('tsk_hash_token', sa.String(length=255), nullable=False))
    #op.drop_column('task', 'tsk_token')
    op.add_column('user', sa.Column('usr_hash_token', sa.String(length=255), nullable=False))
    op.drop_column('user', 'password_hash')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password_hash', mysql.VARCHAR(length=255), nullable=True))
    op.drop_column('user', 'usr_hash_token')
    #op.add_column('task', sa.Column('tsk_token', mysql.VARCHAR(length=255), nullable=False))
    op.drop_column('task', 'tsk_hash_token')
    # ### end Alembic commands ###
