"""Added htk_pin

Revision ID: 82d78d5b49a0
Revises: 9813849edbd0
Create Date: 2021-06-13 12:06:23.250080

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82d78d5b49a0'
down_revision = '9813849edbd0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hashtoken', sa.Column('htk_pin', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('hashtoken', 'htk_pin')
    # ### end Alembic commands ###
