"""first init

Revision ID: ab83e7074ba8
Revises: 
Create Date: 2021-01-31 15:58:21.674163

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab83e7074ba8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accessory',
    sa.Column('acc_name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('acc_name')
    )
    op.create_table('category',
    sa.Column('cat_name', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('cat_name')
    )
    op.create_table('customer',
    sa.Column('cus_id', sa.Integer(), nullable=False),
    sa.Column('cus_title', sa.String(length=64), nullable=True),
    sa.Column('cus_first_name', sa.String(length=255), nullable=True),
    sa.Column('cus_last_name', sa.String(length=255), nullable=True),
    sa.Column('cus_email', sa.String(length=255), nullable=True),
    sa.Column('cus_phone_no', sa.String(length=255), nullable=True),
    sa.Column('cus_street', sa.String(length=255), nullable=True),
    sa.Column('cus_house_number', sa.String(length=64), nullable=True),
    sa.Column('cus_post_code', sa.String(length=64), nullable=True),
    sa.Column('cus_awo_member', sa.Boolean(), server_default='0', nullable=False),
    sa.PrimaryKeyConstraint('cus_id')
    )
    op.create_index(op.f('ix_customer_cus_email'), 'customer', ['cus_email'], unique=False)
    op.create_index(op.f('ix_customer_cus_first_name'), 'customer', ['cus_first_name'], unique=False)
    op.create_index(op.f('ix_customer_cus_house_number'), 'customer', ['cus_house_number'], unique=False)
    op.create_index(op.f('ix_customer_cus_last_name'), 'customer', ['cus_last_name'], unique=False)
    op.create_index(op.f('ix_customer_cus_phone_no'), 'customer', ['cus_phone_no'], unique=False)
    op.create_index(op.f('ix_customer_cus_post_code'), 'customer', ['cus_post_code'], unique=False)
    op.create_index(op.f('ix_customer_cus_street'), 'customer', ['cus_street'], unique=False)
    op.create_index(op.f('ix_customer_cus_title'), 'customer', ['cus_title'], unique=False)
    op.create_table('device',
    sa.Column('dev_id', sa.Integer(), nullable=False),
    sa.Column('dev_name', sa.String(length=255), nullable=True),
    sa.Column('dev_model', sa.String(length=255), nullable=True),
    sa.Column('dev_category', sa.String(length=64), nullable=True),
    sa.Column('dev_electronic_mechanical_type', sa.String(length=64), nullable=True),
    sa.Column('dev_mnf_name', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('dev_id')
    )
    op.create_index(op.f('ix_device_dev_category'), 'device', ['dev_category'], unique=False)
    op.create_index(op.f('ix_device_dev_electronic_mechanical_type'), 'device', ['dev_electronic_mechanical_type'], unique=False)
    op.create_index(op.f('ix_device_dev_model'), 'device', ['dev_model'], unique=False)
    op.create_index(op.f('ix_device_dev_name'), 'device', ['dev_name'], unique=False)
    op.create_table('manufacturer',
    sa.Column('mnf_name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('mnf_name')
    )
    op.create_table('state',
    sa.Column('sta_name', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('sta_name')
    )
    op.create_table('step',
    sa.Column('ste_name', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('ste_name')
    )
    op.create_table('user',
    sa.Column('usr_id', sa.Integer(), nullable=False),
    sa.Column('usr_name', sa.String(length=64), nullable=True),
    sa.Column('usr_email', sa.String(length=255), nullable=True),
    sa.Column('usr_email_confirmed_at', sa.DateTime(), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('usr_phone', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('usr_id')
    )
    op.create_index(op.f('ix_user_usr_email'), 'user', ['usr_email'], unique=True)
    op.create_index(op.f('ix_user_usr_name'), 'user', ['usr_name'], unique=True)
    op.create_index(op.f('ix_user_usr_phone'), 'user', ['usr_phone'], unique=False)
    op.create_table('task',
    sa.Column('tsk_id', sa.Integer(), nullable=False),
    sa.Column('tsk_fault_description', sa.String(length=1000), nullable=True),
    sa.Column('tsk_creation_date', sa.DateTime(), nullable=True),
    sa.Column('tsk_state', sa.String(length=64), nullable=True),
    sa.Column('tsk_next_step', sa.String(length=64), nullable=True),
    sa.Column('tsk_cus_id', sa.Integer(), nullable=True),
    sa.Column('tsk_dev_id', sa.Integer(), nullable=True),
    sa.Column('tsk_supervisor_usr_id', sa.Integer(), nullable=True),
    sa.Column('tsk_acc_name', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['tsk_acc_name'], ['accessory.acc_name'], ),
    sa.ForeignKeyConstraint(['tsk_cus_id'], ['customer.cus_id'], ),
    sa.ForeignKeyConstraint(['tsk_dev_id'], ['device.dev_id'], ),
    sa.ForeignKeyConstraint(['tsk_supervisor_usr_id'], ['user.usr_id'], ),
    sa.PrimaryKeyConstraint('tsk_id')
    )
    op.create_index(op.f('ix_task_tsk_next_step'), 'task', ['tsk_next_step'], unique=False)
    op.create_index(op.f('ix_task_tsk_state'), 'task', ['tsk_state'], unique=False)
    op.create_table('usercategory',
    sa.Column('uct_id', sa.Integer(), nullable=False),
    sa.Column('uct_category_name', sa.String(length=64), nullable=True),
    sa.Column('uct_usr_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['uct_usr_id'], ['user.usr_id'], ),
    sa.PrimaryKeyConstraint('uct_id')
    )
    op.create_index(op.f('ix_usercategory_uct_category_name'), 'usercategory', ['uct_category_name'], unique=True)
    op.create_table('image',
    sa.Column('img_id', sa.Integer(), nullable=False),
    sa.Column('img_filename', sa.String(length=255), nullable=False),
    sa.Column('img_tsk_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['img_tsk_id'], ['task.tsk_id'], ),
    sa.PrimaryKeyConstraint('img_id')
    )
    op.create_index(op.f('ix_image_img_filename'), 'image', ['img_filename'], unique=False)
    op.create_table('log',
    sa.Column('log_id', sa.Integer(), nullable=False),
    sa.Column('log_type', sa.String(length=64), nullable=True),
    sa.Column('log_msg', sa.String(length=1000), nullable=True),
    sa.Column('log_timestamp', sa.DateTime(), nullable=False),
    sa.Column('log_usr_id', sa.Integer(), nullable=True),
    sa.Column('log_tsk_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['log_tsk_id'], ['task.tsk_id'], ),
    sa.ForeignKeyConstraint(['log_usr_id'], ['user.usr_id'], ),
    sa.PrimaryKeyConstraint('log_id')
    )
    op.create_index(op.f('ix_log_log_type'), 'log', ['log_type'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_log_log_type'), table_name='log')
    op.drop_table('log')
    op.drop_index(op.f('ix_image_img_filename'), table_name='image')
    op.drop_table('image')
    op.drop_index(op.f('ix_usercategory_uct_category_name'), table_name='usercategory')
    op.drop_table('usercategory')
    op.drop_index(op.f('ix_task_tsk_state'), table_name='task')
    op.drop_index(op.f('ix_task_tsk_next_step'), table_name='task')
    op.drop_table('task')
    op.drop_index(op.f('ix_user_usr_phone'), table_name='user')
    op.drop_index(op.f('ix_user_usr_name'), table_name='user')
    op.drop_index(op.f('ix_user_usr_email'), table_name='user')
    op.drop_table('user')
    op.drop_table('step')
    op.drop_table('state')
    op.drop_table('manufacturer')
    op.drop_index(op.f('ix_device_dev_name'), table_name='device')
    op.drop_index(op.f('ix_device_dev_model'), table_name='device')
    op.drop_index(op.f('ix_device_dev_electronic_mechanical_type'), table_name='device')
    op.drop_index(op.f('ix_device_dev_category'), table_name='device')
    op.drop_table('device')
    op.drop_index(op.f('ix_customer_cus_title'), table_name='customer')
    op.drop_index(op.f('ix_customer_cus_street'), table_name='customer')
    op.drop_index(op.f('ix_customer_cus_post_code'), table_name='customer')
    op.drop_index(op.f('ix_customer_cus_phone_no'), table_name='customer')
    op.drop_index(op.f('ix_customer_cus_last_name'), table_name='customer')
    op.drop_index(op.f('ix_customer_cus_house_number'), table_name='customer')
    op.drop_index(op.f('ix_customer_cus_first_name'), table_name='customer')
    op.drop_index(op.f('ix_customer_cus_email'), table_name='customer')
    op.drop_table('customer')
    op.drop_table('category')
    op.drop_table('accessory')
    # ### end Alembic commands ###
