"""Added link user <-> hashtoken

Revision ID: bdcfd9d3facd
Revises: d15904984ba4
Create Date: 2021-05-21 16:53:46.952020

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bdcfd9d3facd'
down_revision = 'd15904984ba4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hashtoken', sa.Column('htk_usr_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'hashtoken', 'user', ['htk_usr_id'], ['usr_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'hashtoken', type_='foreignkey')
    op.drop_column('hashtoken', 'htk_usr_id')
    # ### end Alembic commands ###
