"""Added user role

Revision ID: cce4f0ae82e7
Revises: bdcfd9d3facd
Create Date: 2021-05-21 17:16:39.879709

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cce4f0ae82e7'
down_revision = 'bdcfd9d3facd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('usr_role', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_user_usr_role'), 'user', ['usr_role'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_usr_role'), table_name='user')
    op.drop_column('user', 'usr_role')
    # ### end Alembic commands ###
