"""Added htk_auth

Revision ID: d15904984ba4
Revises: fd15de63164d
Create Date: 2021-05-20 11:53:35.749987

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd15904984ba4'
down_revision = 'fd15de63164d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hashtoken', sa.Column('htk_auth', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('hashtoken', 'htk_auth')
    # ### end Alembic commands ###
