"""Added HashToken table

Revision ID: fd15de63164d
Revises: 135698105a8d
Create Date: 2021-05-15 14:27:05.346013

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'fd15de63164d'
down_revision = '135698105a8d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hashtoken',
    sa.Column('htk_id', sa.String(length=255), nullable=False),
    sa.Column('htk_tsk_id', sa.Integer(), nullable=True),
    sa.Column('htk_locked', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('htk_creation_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['htk_tsk_id'], ['task.tsk_id'], ),
    sa.PrimaryKeyConstraint('htk_id')
    )
    op.drop_column('task', 'tsk_hash_token')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('tsk_hash_token', mysql.VARCHAR(length=255), nullable=False))
    op.drop_table('hashtoken')
    # ### end Alembic commands ###
